// Snapshot of major US index constituents (Dow 30 / Nasdaq 100 / S&P 500) for browsing & search.
// Finnhub's free tier doesn't expose index constituent data, so this is a static, hand-maintained
// list rather than a live feed — it may drift slightly from the real indices as they rebalance.

export interface IndexedSymbol {
  symbol: string;
  name: string;
}

export const DOW_30: IndexedSymbol[] = [
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "AXP", name: "American Express Co." },
  { symbol: "BA", name: "Boeing Co." },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "CRM", name: "Salesforce Inc." },
  { symbol: "CSCO", name: "Cisco Systems Inc." },
  { symbol: "CVX", name: "Chevron Corp." },
  { symbol: "DIS", name: "Walt Disney Co." },
  { symbol: "GS", name: "Goldman Sachs Group" },
  { symbol: "HD", name: "Home Depot Inc." },
  { symbol: "HON", name: "Honeywell International" },
  { symbol: "IBM", name: "International Business Machines" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "KO", name: "Coca-Cola Co." },
  { symbol: "MCD", name: "McDonald's Corp." },
  { symbol: "MMM", name: "3M Co." },
  { symbol: "MRK", name: "Merck & Co." },
  { symbol: "MSFT", name: "Microsoft Corp." },
  { symbol: "NKE", name: "Nike Inc." },
  { symbol: "NVDA", name: "NVIDIA Corp." },
  { symbol: "PG", name: "Procter & Gamble Co." },
  { symbol: "SHW", name: "Sherwin-Williams Co." },
  { symbol: "TRV", name: "Travelers Companies" },
  { symbol: "UNH", name: "UnitedHealth Group" },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "VZ", name: "Verizon Communications" },
  { symbol: "WMT", name: "Walmart Inc." },
];

export const NASDAQ_100: IndexedSymbol[] = [
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corp." },
  { symbol: "NVDA", name: "NVIDIA Corp." },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)" },
  { symbol: "META", name: "Meta Platforms Inc." },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "TSLA", name: "Tesla Inc." },
  { symbol: "COST", name: "Costco Wholesale Corp." },
  { symbol: "NFLX", name: "Netflix Inc." },
  { symbol: "ASML", name: "ASML Holding" },
  { symbol: "AMD", name: "Advanced Micro Devices" },
  { symbol: "PEP", name: "PepsiCo Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "CSCO", name: "Cisco Systems Inc." },
  { symbol: "TMUS", name: "T-Mobile US Inc." },
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "INTU", name: "Intuit Inc." },
  { symbol: "QCOM", name: "Qualcomm Inc." },
  { symbol: "TXN", name: "Texas Instruments" },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "CMCSA", name: "Comcast Corp." },
  { symbol: "HON", name: "Honeywell International" },
  { symbol: "AMAT", name: "Applied Materials" },
  { symbol: "BKNG", name: "Booking Holdings" },
  { symbol: "ISRG", name: "Intuitive Surgical" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals" },
  { symbol: "PANW", name: "Palo Alto Networks" },
  { symbol: "ADP", name: "Automatic Data Processing" },
  { symbol: "SBUX", name: "Starbucks Corp." },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "MDLZ", name: "Mondelez International" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals" },
  { symbol: "ADI", name: "Analog Devices" },
  { symbol: "PYPL", name: "PayPal Holdings" },
  { symbol: "SNPS", name: "Synopsys Inc." },
  { symbol: "KLAC", name: "KLA Corp." },
  { symbol: "CDNS", name: "Cadence Design Systems" },
  { symbol: "MELI", name: "MercadoLibre Inc." },
  { symbol: "CSX", name: "CSX Corp." },
  { symbol: "MAR", name: "Marriott International" },
  { symbol: "PDD", name: "PDD Holdings" },
  { symbol: "CTAS", name: "Cintas Corp." },
  { symbol: "ORLY", name: "O'Reilly Automotive" },
  { symbol: "ABNB", name: "Airbnb Inc." },
  { symbol: "CRWD", name: "CrowdStrike Holdings" },
  { symbol: "MRVL", name: "Marvell Technology" },
  { symbol: "WDAY", name: "Workday Inc." },
  { symbol: "ROP", name: "Roper Technologies" },
  { symbol: "NXPI", name: "NXP Semiconductors" },
  { symbol: "FTNT", name: "Fortinet Inc." },
  { symbol: "DASH", name: "DoorDash Inc." },
  { symbol: "MNST", name: "Monster Beverage" },
  { symbol: "PCAR", name: "PACCAR Inc." },
  { symbol: "PAYX", name: "Paychex Inc." },
  { symbol: "ODFL", name: "Old Dominion Freight Line" },
  { symbol: "AEP", name: "American Electric Power" },
  { symbol: "ROST", name: "Ross Stores" },
  { symbol: "KDP", name: "Keurig Dr Pepper" },
  { symbol: "CPRT", name: "Copart Inc." },
  { symbol: "EXC", name: "Exelon Corp." },
  { symbol: "FAST", name: "Fastenal Co." },
  { symbol: "IDXX", name: "IDEXX Laboratories" },
  { symbol: "EA", name: "Electronic Arts" },
  { symbol: "BKR", name: "Baker Hughes" },
  { symbol: "CHTR", name: "Charter Communications" },
  { symbol: "VRSK", name: "Verisk Analytics" },
  { symbol: "DXCM", name: "DexCom Inc." },
  { symbol: "XEL", name: "Xcel Energy" },
  { symbol: "CTSH", name: "Cognizant Technology Solutions" },
  { symbol: "GEHC", name: "GE HealthCare Technologies" },
  { symbol: "CSGP", name: "CoStar Group" },
  { symbol: "LULU", name: "Lululemon Athletica" },
  { symbol: "ANSS", name: "Ansys Inc." },
  { symbol: "ZS", name: "Zscaler Inc." },
  { symbol: "TTWO", name: "Take-Two Interactive" },
  { symbol: "ON", name: "ON Semiconductor" },
  { symbol: "DDOG", name: "Datadog Inc." },
  { symbol: "TEAM", name: "Atlassian Corp." },
  { symbol: "ILMN", name: "Illumina Inc." },
  { symbol: "GFS", name: "GlobalFoundries" },
  { symbol: "MCHP", name: "Microchip Technology" },
  { symbol: "BIIB", name: "Biogen Inc." },
  { symbol: "CDW", name: "CDW Corp." },
  { symbol: "KHC", name: "Kraft Heinz Co." },
  { symbol: "WBD", name: "Warner Bros. Discovery" },
  { symbol: "ALGN", name: "Align Technology" },
  { symbol: "SMCI", name: "Super Micro Computer" },
  { symbol: "MDB", name: "MongoDB Inc." },
  { symbol: "EBAY", name: "eBay Inc." },
  { symbol: "ENPH", name: "Enphase Energy" },
  { symbol: "SIRI", name: "Sirius XM Holdings" },
  { symbol: "APP", name: "AppLovin Corp." },
  { symbol: "ARM", name: "Arm Holdings" },
  { symbol: "TTD", name: "Trade Desk Inc." },
  { symbol: "CCEP", name: "Coca-Cola Europacific Partners" },
];

export const SP_500: IndexedSymbol[] = [
  // Information Technology
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corp." },
  { symbol: "NVDA", name: "NVIDIA Corp." },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "ORCL", name: "Oracle Corp." },
  { symbol: "CRM", name: "Salesforce Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "AMD", name: "Advanced Micro Devices" },
  { symbol: "CSCO", name: "Cisco Systems Inc." },
  { symbol: "ACN", name: "Accenture plc" },
  { symbol: "IBM", name: "International Business Machines" },
  { symbol: "TXN", name: "Texas Instruments" },
  { symbol: "INTU", name: "Intuit Inc." },
  { symbol: "QCOM", name: "Qualcomm Inc." },
  { symbol: "NOW", name: "ServiceNow Inc." },
  { symbol: "AMAT", name: "Applied Materials" },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "ADI", name: "Analog Devices" },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "KLAC", name: "KLA Corp." },
  { symbol: "SNPS", name: "Synopsys Inc." },
  { symbol: "CDNS", name: "Cadence Design Systems" },
  { symbol: "PANW", name: "Palo Alto Networks" },
  { symbol: "CRWD", name: "CrowdStrike Holdings" },
  { symbol: "FTNT", name: "Fortinet Inc." },
  { symbol: "ANSS", name: "Ansys Inc." },
  { symbol: "ROP", name: "Roper Technologies" },
  { symbol: "MSI", name: "Motorola Solutions" },
  { symbol: "APH", name: "Amphenol Corp." },
  { symbol: "TEL", name: "TE Connectivity" },
  { symbol: "GLW", name: "Corning Inc." },
  { symbol: "HPQ", name: "HP Inc." },
  { symbol: "HPE", name: "Hewlett Packard Enterprise" },
  { symbol: "DELL", name: "Dell Technologies" },
  { symbol: "NTAP", name: "NetApp Inc." },
  { symbol: "WDC", name: "Western Digital Corp." },
  { symbol: "STX", name: "Seagate Technology" },
  { symbol: "JNPR", name: "Juniper Networks" },
  { symbol: "FFIV", name: "F5 Inc." },
  { symbol: "GEN", name: "Gen Digital Inc." },
  { symbol: "AKAM", name: "Akamai Technologies" },
  { symbol: "PTC", name: "PTC Inc." },
  { symbol: "TDY", name: "Teledyne Technologies" },
  { symbol: "TER", name: "Teradyne Inc." },
  { symbol: "TRMB", name: "Trimble Inc." },
  { symbol: "KEYS", name: "Keysight Technologies" },
  { symbol: "ZBRA", name: "Zebra Technologies" },
  { symbol: "ON", name: "ON Semiconductor" },
  { symbol: "MPWR", name: "Monolithic Power Systems" },
  { symbol: "SWKS", name: "Skyworks Solutions" },
  { symbol: "QRVO", name: "Qorvo Inc." },
  { symbol: "ENPH", name: "Enphase Energy" },
  { symbol: "FSLR", name: "First Solar Inc." },
  { symbol: "GRMN", name: "Garmin Ltd." },
  { symbol: "EPAM", name: "EPAM Systems" },
  { symbol: "GDDY", name: "GoDaddy Inc." },
  { symbol: "PAYC", name: "Paycom Software" },
  { symbol: "FICO", name: "Fair Isaac Corp." },
  { symbol: "WDAY", name: "Workday Inc." },
  { symbol: "DDOG", name: "Datadog Inc." },
  { symbol: "MCHP", name: "Microchip Technology" },
  { symbol: "CDW", name: "CDW Corp." },
  { symbol: "VRSN", name: "Verisign Inc." },
  { symbol: "JBL", name: "Jabil Inc." },
  { symbol: "IT", name: "Gartner Inc." },

  // Health Care
  { symbol: "UNH", name: "UnitedHealth Group" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "LLY", name: "Eli Lilly and Co." },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "MRK", name: "Merck & Co." },
  { symbol: "TMO", name: "Thermo Fisher Scientific" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "DHR", name: "Danaher Corp." },
  { symbol: "BMY", name: "Bristol-Myers Squibb" },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "MDT", name: "Medtronic plc" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals" },
  { symbol: "ISRG", name: "Intuitive Surgical" },
  { symbol: "CI", name: "Cigna Group" },
  { symbol: "ELV", name: "Elevance Health" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals" },
  { symbol: "HCA", name: "HCA Healthcare" },
  { symbol: "CVS", name: "CVS Health Corp." },
  { symbol: "SYK", name: "Stryker Corp." },
  { symbol: "ZTS", name: "Zoetis Inc." },
  { symbol: "BSX", name: "Boston Scientific" },
  { symbol: "MCK", name: "McKesson Corp." },
  { symbol: "BDX", name: "Becton Dickinson" },
  { symbol: "HUM", name: "Humana Inc." },
  { symbol: "IDXX", name: "IDEXX Laboratories" },
  { symbol: "IQV", name: "IQVIA Holdings" },
  { symbol: "A", name: "Agilent Technologies" },
  { symbol: "EW", name: "Edwards Lifesciences" },
  { symbol: "RMD", name: "ResMed Inc." },
  { symbol: "DXCM", name: "DexCom Inc." },
  { symbol: "BIIB", name: "Biogen Inc." },
  { symbol: "MTD", name: "Mettler-Toledo International" },
  { symbol: "CAH", name: "Cardinal Health" },
  { symbol: "VTRS", name: "Viatris Inc." },
  { symbol: "WAT", name: "Waters Corp." },
  { symbol: "COO", name: "Cooper Companies" },
  { symbol: "ZBH", name: "Zimmer Biomet Holdings" },
  { symbol: "STE", name: "STERIS plc" },
  { symbol: "ALGN", name: "Align Technology" },
  { symbol: "INCY", name: "Incyte Corp." },
  { symbol: "HOLX", name: "Hologic Inc." },
  { symbol: "CRL", name: "Charles River Laboratories" },
  { symbol: "MOH", name: "Molina Healthcare" },
  { symbol: "GEHC", name: "GE HealthCare Technologies" },
  { symbol: "DVA", name: "DaVita Inc." },
  { symbol: "PODD", name: "Insulet Corp." },
  { symbol: "TFX", name: "Teleflex Inc." },
  { symbol: "UHS", name: "Universal Health Services" },
  { symbol: "RVTY", name: "Revvity Inc." },
  { symbol: "WST", name: "West Pharmaceutical Services" },
  { symbol: "BAX", name: "Baxter International" },
  { symbol: "SOLV", name: "Solventum Corp." },
  { symbol: "CNC", name: "Centene Corp." },
  { symbol: "LH", name: "Labcorp Holdings" },
  { symbol: "DGX", name: "Quest Diagnostics" },

  // Financials
  { symbol: "BRK.B", name: "Berkshire Hathaway" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "MA", name: "Mastercard Inc." },
  { symbol: "BAC", name: "Bank of America Corp." },
  { symbol: "WFC", name: "Wells Fargo & Co." },
  { symbol: "GS", name: "Goldman Sachs Group" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "SPGI", name: "S&P Global Inc." },
  { symbol: "AXP", name: "American Express Co." },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "SCHW", name: "Charles Schwab Corp." },
  { symbol: "BLK", name: "BlackRock Inc." },
  { symbol: "PGR", name: "Progressive Corp." },
  { symbol: "CB", name: "Chubb Ltd." },
  { symbol: "MMC", name: "Marsh & McLennan" },
  { symbol: "AON", name: "Aon plc" },
  { symbol: "ICE", name: "Intercontinental Exchange" },
  { symbol: "CME", name: "CME Group Inc." },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "PNC", name: "PNC Financial Services" },
  { symbol: "TFC", name: "Truist Financial" },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co." },
  { symbol: "MCO", name: "Moody's Corp." },
  { symbol: "TRV", name: "Travelers Companies" },
  { symbol: "AFL", name: "Aflac Inc." },
  { symbol: "MET", name: "MetLife Inc." },
  { symbol: "AIG", name: "American International Group" },
  { symbol: "PRU", name: "Prudential Financial" },
  { symbol: "ALL", name: "Allstate Corp." },
  { symbol: "COF", name: "Capital One Financial" },
  { symbol: "BK", name: "Bank of New York Mellon" },
  { symbol: "STT", name: "State Street Corp." },
  { symbol: "FIS", name: "Fidelity National Information Services" },
  { symbol: "FI", name: "Fiserv Inc." },
  { symbol: "GPN", name: "Global Payments Inc." },
  { symbol: "DFS", name: "Discover Financial Services" },
  { symbol: "NDAQ", name: "Nasdaq Inc." },
  { symbol: "TROW", name: "T. Rowe Price Group" },
  { symbol: "AMP", name: "Ameriprise Financial" },
  { symbol: "BRO", name: "Brown & Brown Inc." },
  { symbol: "WTW", name: "Willis Towers Watson" },
  { symbol: "ACGL", name: "Arch Capital Group" },
  { symbol: "MTB", name: "M&T Bank Corp." },
  { symbol: "HBAN", name: "Huntington Bancshares" },
  { symbol: "RF", name: "Regions Financial" },
  { symbol: "CFG", name: "Citizens Financial Group" },
  { symbol: "FITB", name: "Fifth Third Bancorp" },
  { symbol: "KEY", name: "KeyCorp" },
  { symbol: "SYF", name: "Synchrony Financial" },
  { symbol: "NTRS", name: "Northern Trust Corp." },
  { symbol: "CBOE", name: "Cboe Global Markets" },
  { symbol: "CINF", name: "Cincinnati Financial" },
  { symbol: "L", name: "Loews Corp." },
  { symbol: "GL", name: "Globe Life Inc." },
  { symbol: "IVZ", name: "Invesco Ltd." },
  { symbol: "JKHY", name: "Jack Henry & Associates" },
  { symbol: "PFG", name: "Principal Financial Group" },
  { symbol: "ERIE", name: "Erie Indemnity Co." },
  { symbol: "WRB", name: "W. R. Berkley Corp." },
  { symbol: "MKTX", name: "MarketAxess Holdings" },
  { symbol: "RJF", name: "Raymond James Financial" },
  { symbol: "HIG", name: "Hartford Financial Services" },
  { symbol: "BEN", name: "Franklin Resources" },
  { symbol: "PYPL", name: "PayPal Holdings" },

  // Consumer Discretionary
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "TSLA", name: "Tesla Inc." },
  { symbol: "HD", name: "Home Depot Inc." },
  { symbol: "MCD", name: "McDonald's Corp." },
  { symbol: "BKNG", name: "Booking Holdings" },
  { symbol: "LOW", name: "Lowe's Companies" },
  { symbol: "TJX", name: "TJX Companies" },
  { symbol: "SBUX", name: "Starbucks Corp." },
  { symbol: "NKE", name: "Nike Inc." },
  { symbol: "CMG", name: "Chipotle Mexican Grill" },
  { symbol: "ORLY", name: "O'Reilly Automotive" },
  { symbol: "MAR", name: "Marriott International" },
  { symbol: "GM", name: "General Motors Co." },
  { symbol: "F", name: "Ford Motor Co." },
  { symbol: "HLT", name: "Hilton Worldwide Holdings" },
  { symbol: "YUM", name: "Yum! Brands" },
  { symbol: "ABNB", name: "Airbnb Inc." },
  { symbol: "AZO", name: "AutoZone Inc." },
  { symbol: "ROST", name: "Ross Stores" },
  { symbol: "DHI", name: "D.R. Horton Inc." },
  { symbol: "LEN", name: "Lennar Corp." },
  { symbol: "LVS", name: "Las Vegas Sands Corp." },
  { symbol: "EBAY", name: "eBay Inc." },
  { symbol: "DRI", name: "Darden Restaurants" },
  { symbol: "NVR", name: "NVR Inc." },
  { symbol: "PHM", name: "PulteGroup Inc." },
  { symbol: "ULTA", name: "Ulta Beauty Inc." },
  { symbol: "EXPE", name: "Expedia Group" },
  { symbol: "TSCO", name: "Tractor Supply Co." },
  { symbol: "BBY", name: "Best Buy Co." },
  { symbol: "RL", name: "Ralph Lauren Corp." },
  { symbol: "GPC", name: "Genuine Parts Co." },
  { symbol: "KMX", name: "CarMax Inc." },
  { symbol: "POOL", name: "Pool Corp." },
  { symbol: "WYNN", name: "Wynn Resorts" },
  { symbol: "CCL", name: "Carnival Corp." },
  { symbol: "RCL", name: "Royal Caribbean Cruises" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings" },
  { symbol: "MGM", name: "MGM Resorts International" },
  { symbol: "DPZ", name: "Domino's Pizza" },
  { symbol: "LKQ", name: "LKQ Corp." },
  { symbol: "BWA", name: "BorgWarner Inc." },
  { symbol: "APTV", name: "Aptiv plc" },
  { symbol: "DECK", name: "Deckers Brands" },
  { symbol: "TPR", name: "Tapestry Inc." },
  { symbol: "CZR", name: "Caesars Entertainment" },
  { symbol: "HAS", name: "Hasbro Inc." },

  // Consumer Staples
  { symbol: "PG", name: "Procter & Gamble Co." },
  { symbol: "KO", name: "Coca-Cola Co." },
  { symbol: "PEP", name: "PepsiCo Inc." },
  { symbol: "COST", name: "Costco Wholesale Corp." },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "PM", name: "Philip Morris International" },
  { symbol: "MO", name: "Altria Group" },
  { symbol: "MDLZ", name: "Mondelez International" },
  { symbol: "CL", name: "Colgate-Palmolive Co." },
  { symbol: "KMB", name: "Kimberly-Clark Corp." },
  { symbol: "GIS", name: "General Mills Inc." },
  { symbol: "STZ", name: "Constellation Brands" },
  { symbol: "SYY", name: "Sysco Corp." },
  { symbol: "KDP", name: "Keurig Dr Pepper" },
  { symbol: "KHC", name: "Kraft Heinz Co." },
  { symbol: "HSY", name: "Hershey Co." },
  { symbol: "MKC", name: "McCormick & Co." },
  { symbol: "CHD", name: "Church & Dwight Co." },
  { symbol: "CLX", name: "Clorox Co." },
  { symbol: "TSN", name: "Tyson Foods" },
  { symbol: "KR", name: "Kroger Co." },
  { symbol: "ADM", name: "Archer-Daniels-Midland" },
  { symbol: "TGT", name: "Target Corp." },
  { symbol: "DG", name: "Dollar General Corp." },
  { symbol: "DLTR", name: "Dollar Tree Inc." },
  { symbol: "CAG", name: "Conagra Brands" },
  { symbol: "CPB", name: "Campbell's Co." },
  { symbol: "SJM", name: "J.M. Smucker Co." },
  { symbol: "HRL", name: "Hormel Foods" },
  { symbol: "MNST", name: "Monster Beverage" },
  { symbol: "KVUE", name: "Kenvue Inc." },
  { symbol: "EL", name: "Estee Lauder Companies" },
  { symbol: "BF.B", name: "Brown-Forman Corp." },
  { symbol: "K", name: "Kellanova" },
  { symbol: "TAP", name: "Molson Coors Beverage" },
  { symbol: "LW", name: "Lamb Weston Holdings" },

  // Energy
  { symbol: "XOM", name: "Exxon Mobil Corp." },
  { symbol: "CVX", name: "Chevron Corp." },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "EOG", name: "EOG Resources" },
  { symbol: "SLB", name: "Schlumberger (SLB)" },
  { symbol: "MPC", name: "Marathon Petroleum" },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "VLO", name: "Valero Energy" },
  { symbol: "WMB", name: "Williams Companies" },
  { symbol: "OKE", name: "ONEOK Inc." },
  { symbol: "KMI", name: "Kinder Morgan" },
  { symbol: "OXY", name: "Occidental Petroleum" },
  { symbol: "HES", name: "Hess Corp." },
  { symbol: "BKR", name: "Baker Hughes" },
  { symbol: "HAL", name: "Halliburton Co." },
  { symbol: "DVN", name: "Devon Energy" },
  { symbol: "FANG", name: "Diamondback Energy" },
  { symbol: "TRGP", name: "Targa Resources" },
  { symbol: "CTRA", name: "Coterra Energy" },
  { symbol: "EQT", name: "EQT Corp." },
  { symbol: "APA", name: "APA Corp." },

  // Industrials
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "RTX", name: "RTX Corp." },
  { symbol: "UNP", name: "Union Pacific Corp." },
  { symbol: "HON", name: "Honeywell International" },
  { symbol: "UPS", name: "United Parcel Service" },
  { symbol: "BA", name: "Boeing Co." },
  { symbol: "GE", name: "GE Aerospace" },
  { symbol: "DE", name: "Deere & Co." },
  { symbol: "LMT", name: "Lockheed Martin Corp." },
  { symbol: "ADP", name: "Automatic Data Processing" },
  { symbol: "ETN", name: "Eaton Corp." },
  { symbol: "ITW", name: "Illinois Tool Works" },
  { symbol: "NOC", name: "Northrop Grumman Corp." },
  { symbol: "GD", name: "General Dynamics Corp." },
  { symbol: "EMR", name: "Emerson Electric Co." },
  { symbol: "CSX", name: "CSX Corp." },
  { symbol: "NSC", name: "Norfolk Southern Corp." },
  { symbol: "WM", name: "Waste Management Inc." },
  { symbol: "FDX", name: "FedEx Corp." },
  { symbol: "PH", name: "Parker Hannifin Corp." },
  { symbol: "TT", name: "Trane Technologies" },
  { symbol: "CARR", name: "Carrier Global Corp." },
  { symbol: "PCAR", name: "PACCAR Inc." },
  { symbol: "CMI", name: "Cummins Inc." },
  { symbol: "ROK", name: "Rockwell Automation" },
  { symbol: "JCI", name: "Johnson Controls International" },
  { symbol: "OTIS", name: "Otis Worldwide Corp." },
  { symbol: "PAYX", name: "Paychex Inc." },
  { symbol: "GWW", name: "W.W. Grainger Inc." },
  { symbol: "XYL", name: "Xylem Inc." },
  { symbol: "AME", name: "AMETEK Inc." },
  { symbol: "HWM", name: "Howmet Aerospace" },
  { symbol: "FAST", name: "Fastenal Co." },
  { symbol: "VRSK", name: "Verisk Analytics" },
  { symbol: "IEX", name: "IDEX Corp." },
  { symbol: "DOV", name: "Dover Corp." },
  { symbol: "SNA", name: "Snap-on Inc." },
  { symbol: "PWR", name: "Quanta Services" },
  { symbol: "EFX", name: "Equifax Inc." },
  { symbol: "CTAS", name: "Cintas Corp." },
  { symbol: "URI", name: "United Rentals" },
  { symbol: "LDOS", name: "Leidos Holdings" },
  { symbol: "IR", name: "Ingersoll Rand" },
  { symbol: "MAS", name: "Masco Corp." },
  { symbol: "ODFL", name: "Old Dominion Freight Line" },
  { symbol: "LHX", name: "L3Harris Technologies" },
  { symbol: "TDG", name: "TransDigm Group" },
  { symbol: "HII", name: "Huntington Ingalls Industries" },
  { symbol: "TXT", name: "Textron Inc." },
  { symbol: "ALLE", name: "Allegion plc" },
  { symbol: "PNR", name: "Pentair plc" },
  { symbol: "ROL", name: "Rollins Inc." },
  { symbol: "AOS", name: "A. O. Smith Corp." },
  { symbol: "CHRW", name: "C.H. Robinson Worldwide" },
  { symbol: "EXPD", name: "Expeditors International" },
  { symbol: "JBHT", name: "J.B. Hunt Transport Services" },
  { symbol: "LUV", name: "Southwest Airlines" },
  { symbol: "DAL", name: "Delta Air Lines" },
  { symbol: "UAL", name: "United Airlines Holdings" },
  { symbol: "AAL", name: "American Airlines Group" },
  { symbol: "CSGP", name: "CoStar Group" },
  { symbol: "BALL", name: "Ball Corp." },
  { symbol: "PKG", name: "Packaging Corp of America" },
  { symbol: "NDSN", name: "Nordson Corp." },

  // Materials
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "APD", name: "Air Products and Chemicals" },
  { symbol: "SHW", name: "Sherwin-Williams Co." },
  { symbol: "ECL", name: "Ecolab Inc." },
  { symbol: "FCX", name: "Freeport-McMoRan" },
  { symbol: "NEM", name: "Newmont Corp." },
  { symbol: "DD", name: "DuPont de Nemours" },
  { symbol: "DOW", name: "Dow Inc." },
  { symbol: "PPG", name: "PPG Industries" },
  { symbol: "VMC", name: "Vulcan Materials" },
  { symbol: "MLM", name: "Martin Marietta Materials" },
  { symbol: "IFF", name: "International Flavors & Fragrances" },
  { symbol: "ALB", name: "Albemarle Corp." },
  { symbol: "CE", name: "Celanese Corp." },
  { symbol: "AVY", name: "Avery Dennison Corp." },
  { symbol: "NUE", name: "Nucor Corp." },
  { symbol: "STLD", name: "Steel Dynamics" },
  { symbol: "CF", name: "CF Industries Holdings" },
  { symbol: "MOS", name: "Mosaic Co." },
  { symbol: "FMC", name: "FMC Corp." },
  { symbol: "EMN", name: "Eastman Chemical Co." },
  { symbol: "LYB", name: "LyondellBasell Industries" },

  // Real Estate
  { symbol: "PLD", name: "Prologis Inc." },
  { symbol: "AMT", name: "American Tower Corp." },
  { symbol: "EQIX", name: "Equinix Inc." },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "O", name: "Realty Income Corp." },
  { symbol: "WELL", name: "Welltower Inc." },
  { symbol: "SPG", name: "Simon Property Group" },
  { symbol: "DLR", name: "Digital Realty Trust" },
  { symbol: "CCI", name: "Crown Castle Inc." },
  { symbol: "CBRE", name: "CBRE Group" },
  { symbol: "VICI", name: "VICI Properties" },
  { symbol: "EXR", name: "Extra Space Storage" },
  { symbol: "AVB", name: "AvalonBay Communities" },
  { symbol: "EQR", name: "Equity Residential" },
  { symbol: "AMH", name: "American Homes 4 Rent" },
  { symbol: "INVH", name: "Invitation Homes" },
  { symbol: "MAA", name: "Mid-America Apartment Communities" },
  { symbol: "ESS", name: "Essex Property Trust" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities" },
  { symbol: "KIM", name: "Kimco Realty" },
  { symbol: "REG", name: "Regency Centers" },
  { symbol: "VTR", name: "Ventas Inc." },
  { symbol: "BXP", name: "BXP Inc." },
  { symbol: "HST", name: "Host Hotels & Resorts" },
  { symbol: "UDR", name: "UDR Inc." },
  { symbol: "CPT", name: "Camden Property Trust" },
  { symbol: "FRT", name: "Federal Realty Investment Trust" },
  { symbol: "IRM", name: "Iron Mountain Inc." },
  { symbol: "WY", name: "Weyerhaeuser Co." },

  // Utilities
  { symbol: "NEE", name: "NextEra Energy" },
  { symbol: "DUK", name: "Duke Energy Corp." },
  { symbol: "SO", name: "Southern Co." },
  { symbol: "D", name: "Dominion Energy" },
  { symbol: "AEP", name: "American Electric Power" },
  { symbol: "EXC", name: "Exelon Corp." },
  { symbol: "SRE", name: "Sempra" },
  { symbol: "XEL", name: "Xcel Energy" },
  { symbol: "PEG", name: "Public Service Enterprise Group" },
  { symbol: "ED", name: "Consolidated Edison" },
  { symbol: "WEC", name: "WEC Energy Group" },
  { symbol: "ES", name: "Eversource Energy" },
  { symbol: "EIX", name: "Edison International" },
  { symbol: "FE", name: "FirstEnergy Corp." },
  { symbol: "PPL", name: "PPL Corp." },
  { symbol: "AWK", name: "American Water Works" },
  { symbol: "DTE", name: "DTE Energy Co." },
  { symbol: "AEE", name: "Ameren Corp." },
  { symbol: "CMS", name: "CMS Energy Corp." },
  { symbol: "CNP", name: "CenterPoint Energy" },
  { symbol: "ATO", name: "Atmos Energy Corp." },
  { symbol: "NI", name: "NiSource Inc." },
  { symbol: "LNT", name: "Alliant Energy Corp." },
  { symbol: "EVRG", name: "Evergy Inc." },
  { symbol: "PNW", name: "Pinnacle West Capital" },
  { symbol: "NRG", name: "NRG Energy" },
  { symbol: "PCG", name: "PG&E Corp." },

  // Communication Services
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)" },
  { symbol: "META", name: "Meta Platforms Inc." },
  { symbol: "NFLX", name: "Netflix Inc." },
  { symbol: "DIS", name: "Walt Disney Co." },
  { symbol: "CMCSA", name: "Comcast Corp." },
  { symbol: "VZ", name: "Verizon Communications" },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "TMUS", name: "T-Mobile US Inc." },
  { symbol: "CHTR", name: "Charter Communications" },
  { symbol: "EA", name: "Electronic Arts" },
  { symbol: "TTWO", name: "Take-Two Interactive" },
  { symbol: "WBD", name: "Warner Bros. Discovery" },
  { symbol: "OMC", name: "Omnicom Group" },
  { symbol: "IPG", name: "Interpublic Group" },
  { symbol: "LYV", name: "Live Nation Entertainment" },
  { symbol: "MTCH", name: "Match Group Inc." },
  { symbol: "FOXA", name: "Fox Corp. (Class A)" },
  { symbol: "FOX", name: "Fox Corp. (Class B)" },
  { symbol: "NWSA", name: "News Corp. (Class A)" },
  { symbol: "NWS", name: "News Corp. (Class B)" },
];

export type IndexKey = "DOW" | "NASDAQ100" | "SP500";

export const INDEX_META: Record<IndexKey, { label: string; list: IndexedSymbol[] }> = {
  DOW: { label: "Dow 30", list: DOW_30 },
  NASDAQ100: { label: "Nasdaq 100", list: NASDAQ_100 },
  SP500: { label: "S&P 500", list: SP_500 },
};

export interface UniverseEntry extends IndexedSymbol {
  indices: IndexKey[];
}

function buildUniverse(): UniverseEntry[] {
  const map = new Map<string, UniverseEntry>();
  (Object.keys(INDEX_META) as IndexKey[]).forEach((key) => {
    INDEX_META[key].list.forEach(({ symbol, name }) => {
      const existing = map.get(symbol);
      if (existing) {
        if (!existing.indices.includes(key)) existing.indices.push(key);
      } else {
        map.set(symbol, { symbol, name, indices: [key] });
      }
    });
  });
  return Array.from(map.values()).sort((a, b) => a.symbol.localeCompare(b.symbol));
}

export const MARKET_UNIVERSE: UniverseEntry[] = buildUniverse();

export function searchUniverse(query: string, limit = 50): UniverseEntry[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  return MARKET_UNIVERSE.filter((e) => e.symbol.includes(q) || e.name.toUpperCase().includes(q)).slice(0, limit);
}
